const data = [
  {
    id: 1,
    appli_name: "PSC1855",
    customer_name: "Shweta Chopade",
    contact: "8347384727",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 2,
    appli_name: "PSC1858",
    customer_name: "Neha Patil",
    contact: "neha@gmail.com",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 3,
    appli_name: "PSC1857",
    customer_name: "shusmita chavhan",
    contact: "8347384727",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 4,
    appli_name: "PSC1895",
    customer_name: "raj patil",
    contact: "raj@gmail.com",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    appli_name: "PSC1858",
    customer_name: "Neha Patil",
    contact: "neha@gmail.com",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 6,
    appli_name: "PSC1855",
    customer_name: "Shweta Chopade",
    contact: "8347384727",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 7,
    appli_name: "PSC1855",
    customer_name: "Shweta Chopade",
    contact: "8347384727",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 8,
    appli_name: "PSC1858",
    customer_name: "Neha Patil",
    contact: "neha@gmail.com",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 9,
    appli_name: "PSC1855",
    customer_name: "Shweta Chopade",
    contact: "8347384727",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
  {
    id: 10,
    appli_name: "PSC1858",
    customer_name: "Neha Patil",
    contact: "neha@gmail.com",
    total_amount: "0/-",
    status: "Pending",
    pay_status: "unpaid",
  },
];
export { data };
