const userdata = [
  {
    DistrictName: "Raigad",
    CityName: "Kharghar",
    Created_Date: "-01-30 202310:14:41",
    Submited_Name: "-",
    Employee_Name: "",
    Remark: "demo",
  },
  // {
  //   DistrictName: "munbai",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "pune",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
  // {
  //   DistrictName: "Raigad",
  //   CityName: "Kharghar",
  //   Created_Date: "-01-30 202310:14:41",
  //   Submited_Name: "-",
  //   Employee_Name: "",
  //   Remark: "demo",
  // },
];
export { userdata };
